### ISSUE TITLE
关于设计中修改时钟配置的问题。

### ISSUE THREAD

**Issue by AlphaStar1122** [cjhonlyone/ADC-lvds#4]
您好，在此项目中我想把MMCM的输入变成单端输入，来适配开发板的管脚，请问我是自建一个新的IP核还是修改原工程中的MMCM模块配置，如要修改配置参数要修改哪里呢。

**Comment by cjhonlyone** [comment]
mmcm原语提供的是单端端口，你可以增加一个差分转单端原语‘IBUF’，具体如何修改你可以google一下相应的文档。
或者自建一个新的IP核也可以，图像界面配置更容易一些。

**Comment by AlphaStar1122** [comment]
如果创建一个MMCM的IP核在Implementation时会与AdcClock冲突，请问AdcClock与MMCM的关系是什么样的。

**Comment by cjhonlyone** [comment]
AdcClock与mmcm IP等价，你需要替换AdcClock为你的mmcm IP

**Comment by AlphaStar1122** [comment]
感谢您的指教。
